
spring:
  data:
    mongodb:
      host: database-auth
      database: auth_db
      port: 27017
      # username: user
      # password: ${MONGODB_PASSWORD}   

signing:
  key: 345345fsdfsf5345      